### ISSUE TITLE
Check out flatjson

### ISSUE THREAD

**Issue by twpayne** [devopsfaith/flatmap#2]
Check out https://github.com/twpayne/flatjson - it seems quite similar to what you're working on here.

Feel free to close this issue as spam :)

**Comment by kpacha** [comment]
hi @twpayne 

thanks for the tip! we already checked out that and other available implementations and no one covered the exact use-case we needed: 

- flatten a map
- add, delete and move/rename elements nested in maps and collections
- expand the result

the lib you are pointing required us to marshal the struct before flattening it and unmarshal the final result and, from our experience, the json encoding package is not the most performant on the standard lib. We need this feature to be able to run on every response served by our api gateway, so
performance is critical. That's why we are already testing an alternative implementation [github.com/devopsfaith/flatmap/tree](https://github.com/devopsfaith/flatmap/tree/master/tree)

**Comment by twpayne** [comment]
Thanks for the comprehensive feedback :)
